site_name: ReghTechLab Documentation
site_description: Documentation for the ReghTechLab Portfolio & Blog Application
site_author: Abraham Regha

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started: setup.md
  - Features:
    - Authentication: features/authentication.md
    - Blog & Community: features/blog.md
  - Architecture:
    - Database Models: architecture/database.md
